va_evaluation:
  description: 'Evalutions PVA'
  fields:
    id:
      type: integer
      not null: true
      description: 'Primary key'
      unsigned: true
      auto_increment: true
      length: 20
    create_time:
      type: varchar
      length: 19
      description: 'Date and Time'
    user:
      type: varchar
      length: 70
      description: 'User ID'
    langcode:
      type: varchar
      length: 10
      description: 'Current Langcode'
    type_evaluation:
      type: varchar
      length: 20
      description: 'Type of Evaluation'
    nid_0:
      type: varchar
      length: 20
      description: 'Selected Value'      
    nid_1:
      type: varchar
      length: 20
      description: 'Selected Value'
    nid_2:
      type: varchar
      length: 20
      description: 'Selected Value'
    nid_3:
      type: varchar
      length: 20
      description: 'Selected Value'
    nid_4:
      type: varchar
      length: 20
      description: 'Selected Value'
    nid_5:
      type: varchar
      length: 20
      description: 'Selected Value'
    nid_6:
      type: varchar
      length: 20
      description: 'Selected Value'
    nid_7:
      type: varchar
      length: 20
      description: 'Selected Value'
    nid_8:
      type: varchar
      length: 20
      description: 'Selected Value'
    nid_9:
      type: varchar
      length: 20
      description: 'Selected Value'
